// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYlLPgvzOgUWmIpx470un6C-sQzYrX6Ro',
    appId: '1:502097116145:web:5b43bbcad8326e0a3f2250',
    messagingSenderId: '502097116145',
    projectId: 'fir-auth-practice-2f04e',
    authDomain: 'fir-auth-practice-2f04e.firebaseapp.com',
    storageBucket: 'fir-auth-practice-2f04e.firebasestorage.app',
    measurementId: 'G-3Q6104MMJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJubSEzM75G5cJWhMwBji_9r2hetTre0g',
    appId: '1:502097116145:android:2d119a31e15786eb3f2250',
    messagingSenderId: '502097116145',
    projectId: 'fir-auth-practice-2f04e',
    storageBucket: 'fir-auth-practice-2f04e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb2cySihD9PxutVUmMF6STNyG_Om7sFTc',
    appId: '1:502097116145:ios:ac291ad76d9add3c3f2250',
    messagingSenderId: '502097116145',
    projectId: 'fir-auth-practice-2f04e',
    storageBucket: 'fir-auth-practice-2f04e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb2cySihD9PxutVUmMF6STNyG_Om7sFTc',
    appId: '1:502097116145:ios:ac291ad76d9add3c3f2250',
    messagingSenderId: '502097116145',
    projectId: 'fir-auth-practice-2f04e',
    storageBucket: 'fir-auth-practice-2f04e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYlLPgvzOgUWmIpx470un6C-sQzYrX6Ro',
    appId: '1:502097116145:web:116dce6c4b6285a13f2250',
    messagingSenderId: '502097116145',
    projectId: 'fir-auth-practice-2f04e',
    authDomain: 'fir-auth-practice-2f04e.firebaseapp.com',
    storageBucket: 'fir-auth-practice-2f04e.firebasestorage.app',
    measurementId: 'G-XBP1JT7B0E',
  );
}
